### ISSUE TITLE
레디스 연동

### ISSUE THREAD

**Issue by tbonelee** [f-lab-edu/ticket-booking#2]
JWT 토큰을 로그아웃 처리하기 위해 필요

**Comment by tbonelee** [comment]
@hsw0905 이번 이슈 같은 경우에는 우선은 로컬 메모리 캐시 같은 것을 사용하고 나중에 필요에 따라 디비를 달거나 하는 것이 프로젝트 진행 속도를 내기에 조금 더 나을 것 같아서 우선은 미뤄둘까 하는데 괜찮으실까요..??

**Comment by hsw0905** [comment]
@tbonelee 넵 로컬에서 도커로 돌리거나 하면 될 것 같습니다

**Comment by tbonelee** [comment]
Fixed by #30
