### ISSUE TITLE
익셉션 처리

### ISSUE THREAD

**Issue by hsw0905** [f-lab-edu/ticket-booking#25]
두 가지 방향

1. 가급적 예외가 발생하는 곳에서 직접 처리해서 위로 퍼져나가지 않도록
2. 가급적 내부에서 catch하지 않고 예외 핸들러를 통해 처리

저번 멘토링 시간에 논의가 있었던 두 케이스가 있었는데요

결론부터 말씀드리면 - @ExceptionHandler @ExceptionAdvice 를 적극 활용하는 방법으로 통일하는 것이 좋지 않을까 생각됩니다.

1번 케이스의 경우 직접 커스텀 익셉션을 만들게 되는데요 예를들면 이런식으로 BaseException 클래스에 에러 형태를 정의하고
각 도메인에서 에러가 발생할 때마다 BaseException을 상속받는 익셉션 클래스를 새로 만드는? 방식을 생각해 볼 수 있을 것 같습니다. 
```java
@Getter
public class BaseException extends RuntimeException {

    private final String errorCode;

    public BaseException(String errorCode, String message) {
        super(message);
        this.errorCode = errorCode;
    }

    public ErrorResponse toResponse() {
        return new ErrorResponse(getErrorCode(), getMessage());
    }
}
```
이렇게 되면 코드에 try catch 구문이 많이 생기게 되어 코드가 복잡해질 것 같습니다.

따라서 대안은, 스프링에서 제공하는 @ExceptionHandler @ExceptionAdvice를 사용하여
마치 컨트롤러에 Exception처리 AOP가 적용된거 같은? 효과를 주는 방법이 나중에 코드를 보기에 더 나을 것 같습니다.

**Comment by tbonelee** [comment]
저도 공통 로직으로 최대한 빼서 `@ControllerAdvice`를 통해 전역으로 처리하면 좋을 것 같습니다.
커스텀 예외나 예외 처리 부분(`@ExceptionHandler` or `@ExceptionAdvice`)는 기능 구현하면서 필요할 때 추가하면 될까요??

**Comment by tbonelee** [comment]
Fixed by #32
