### ISSUE TITLE
프로젝트 설정 yml 작성

### ISSUE THREAD

**Issue by hsw0905** [f-lab-edu/ticket-booking#5]
설정 파일별 prod, dev, test 환경 분리하여 구분합니다.
- db, redis, jwt, oauth, logging 등등 각종 설정 

<예시>
- application.yml
- application-dev.yml
- application-prod.yml
- application-test.yml

**Comment by tbonelee** [comment]
application 설정 관련 스프링 부트 문서입니다
[https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.files](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.files)
