### ISSUE TITLE
프로젝트 컨벤션 협의

### ISSUE THREAD

**Issue by tbonelee** [f-lab-edu/ticket-booking#8]
- 코드 스타일
- 간단한 이슈 / 커밋 컨벤션
그 외 또 필요한 것이 있으면 말씀해주세요

**Comment by tbonelee** [comment]
자바 코딩 컨벤션은 멘토님이 말씀해주셨던 구글 자바 포맷 플러그인으로 맞추면 어떨까요??
https://plugins.jetbrains.com/plugin/8527-google-java-format
https://bbubbush.tistory.com/29

**Comment by hsw0905** [comment]
네 저도 구글 컨벤션으로 맞추는 것이 좋을 것 같습니다

**Comment by hsw0905** [comment]
레이어 계층을 좀 더 명확하게 역할 구분해보는게 어떨까요?

[as-is]
- 현재 모든 로직이 서비스 클래스 내부에서 처리되고 있습니다.
- 그러다보니, 서비스 계층이 무의미하며, 객체란 단순히 데이터 덩어리 역할만 하게 됩니다. (트랜젝션 스크립트 방식)
- 도메인 계층의 Member는 현재 상태만 있으며 행동[메소드]가 없는 상태입니다.

[to-be]
- 서비스 클래스는 트랜잭션과 도메인 간의 순서만 보장합니다.
- 비즈니스 로직은 도메인 계층에서 처리합니다.

**Comment by tbonelee** [comment]
> 레이어 계층을 좀 더 명확하게 역할 구분해보는게 어떨까요?
> 
> 
> 
> [as-is]
> 
> - 현재 모든 로직이 서비스 클래스 내부에서 처리되고 있습니다.
> 
> - 그러다보니, 서비스 계층이 무의미하며, 객체란 단순히 데이터 덩어리 역할만 하게 됩니다. (트랜잭션 스크립트 방식)
> 
> - 도메인 계층의 Member는 현재 상태만 있으며 행동[메소드]가 없는 상태입니다.
> 
> 
> 
> [to-be]
> 
> - 서비스 클래스는 트랜잭션과 도메인 간의 순서만 보장합니다.
> 
> - 비즈니스 로직은 도메인 계층에서 처리합니다.

피드백 감사합니다!

말씀하신 대로 OOP적인 관점이 많이 부족했던 것 같아서 새롭게 다시 작성하는 게 나을 거 같다는 생각이 들긴 합니다..

이번 피알은 우선은 클로즈할게요!

**Comment by tbonelee** [comment]
어제 멘토링 시간에 얘기했던 외부/컨트롤러/서비스 사이의 데이터 전달 방식을 통일하는 부분에 대해서 제가 이해한 방식이 맞는지 확인 + 어제 마무리 짓지 못 한 부분에 대해 같이 얘기해보려고 합니다!

(모바일로 작성해서 가독성이 떨어질 수 있는 점은 양해부탁드립니다)

## 외부 -> 컨트롤러

"무슨무슨Request"류의 클래스를 작성하고 가급적 자바 valid어노테이션을 통해 유효성 검사
그렇게 하기 힘든 경우 컨트롤러에서 처리

## 컨트롤러 -> 서비스
DTO 클래스 작성 후 컨트롤러에서 변환하여 서비스에 전달

## 서비스 -> 컨트롤러
아직 얘기 안 한 부분..?
생각해 본 방안들
1. 서비스에서 엔티티 반환 후 컨트롤러에서 응답dto로 변환하여 응답
2. 서비스에서 응답 dto로 변환하여 반환
3. 서비스에서 dto로 변환 후 컨트롤러에서 응답 dto로 변환하여 반환(두 dto는 독립적)

우선 저는 1.을 선호합니다.
2.의 경우 어제 얘기 나눴던 것처럼 외부 스펙에 종속적일 수 있기 때문에 배제했구요.
3.의 경우에는 서비스에 dto변환 로직이 들어가면 순수 서비스 로직으로 남기기 어려워지지 않나 하는 생각으로 1.이 조금 더 낫다고 생각했습니다.

선웅님은 어떤 쪽을 생각하셨는지 편하게 말씀해주세요! ("상황에 따라 맞추는 것을 선호"와 같은 의견을 주셔도 괜찮습니다)

**Comment by tbonelee** [comment]
## 비지니스 로직을 어디서 처리할 지에 대한 방향성

- 서비스 컴포넌트에서 가급적 처리
- 단순 레포지토리 작업에 로직이 들어가는 경우 DAO작성

**Comment by tbonelee** [comment]
## 익셉션 처리를 어디서 할 지

두 가지 방향
- 가급적 예외가 발생하는 곳에서 직접 처리해서 위로 퍼져나가지 않도록
- 가급적 내부에서 catch하지 않고 예외 핸들러를 통해 처리

그 때는 두번째 방향으로 얘기가 기울었던 거 같은데 확실히 정해지진 않았던 것 같아서 이슈로 남기는 게 좋을 것 같습니다!

### Reference
https://www.baeldung.com/exception-handling-for-rest-with-spring
https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc
https://mangkyu.tistory.com/204
https://mangkyu.tistory.com/205

**Comment by hsw0905** [comment]
서비스 -> 컨트롤러
넵 저도 1번을 선호하고 상황에 따라 맞추는게 좋은 것 같습니다 !

**Comment by tbonelee** [comment]
End of discussion.
